(function($) {
    $(document).ready(function() {
	
	$('#Rplot').scianimator({
	   'images': ['Albert Lortzing Der Waffenschmied/Der Waffenschmied,1,01,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,1,02,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,1,03,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,1,04,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,1,05,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,1,06,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,1,07,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,1,08,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,1,09,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,1,10,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,1,11,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,1,12,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,2,01,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,2,02,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,2,03,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,2,04,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,2,05,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,2,06,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,2,07,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,2,08,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,2,09,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,2,10,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,2,11,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,2,12,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,2,13,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,2,14,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,2,15,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,3,01,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,3,02,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,3,03,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,3,04,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,3,05,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,3,06,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,3,07,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,3,08,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,3,09,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,3,10,_scenering.svg','Albert Lortzing Der Waffenschmied/Der Waffenschmied,3,11,_scenering.svg'],
	    'width': 720,
	    'delay': 1500,
	    'loopMode': 'loop'
	});
	$('#Rplot').scianimator('play');
    });
})(jQuery);
